import * as React from "react";

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      rel="preload"
      href="/fonts/ABCROM-Bold-Trial.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="romBold"
    />,
    <link
      rel="preload"
      href="/fonts/ABCROM-BoldItalic-Trial.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="romBoldItalic"
    />,
    <link
      rel="preload"
      href="/fonts/ABCROM-Medium-Trial.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="romMedium"
    />,
    <link
      rel="preload"
      href="/fonts/ABCROM-MediumItalic-Trial.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="romMediumItalic"
    />,
    <link
      rel="preload"
      href="/fonts/ABCROM-Book-Trial.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="romBook"
    />,
    <link
      rel="preload"
      href="/fonts/ABCROM-BookItalic-Trial.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="romBookItalic"
    />,
    <link
      rel="preload"
      href="/fonts/ABCROM-Regular-Trial.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="romRegular"
    />,
    <link
      rel="preload"
      href="/fonts/ABCROM-RegularItalic-Trial.woff2"
      as="font"
      type="font/woff2"
      crossOrigin="anonymous"
      key="romRegularItalic"
    />,
  ]);
};
