import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/mode-toggle";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Noah Michaels",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={jetBrainsMono.className}
      suppressHydrationWarning
    >
      <body className="flex items-center justify-center min-h-dvh">
        <ThemeProvider attribute="class">
          <div className="fixed bottom-4 right-4">
            <ModeToggle />
          </div>
          <div className="m-4 prose prose-stone dark:prose-invert">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
